routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
Route::get('/', function ()
{
    if(Auth::check()){
        return redirect()->intended('account/app/dashboard');
    }else{
        return redirect()->intended('account/signin');
    }
});
/*
|-------------------------------------------------------------------------


/*
|--------------------------------------------------------------------------
| Account/Auth Routes
*/
Route::group(['namespace' => 'Account', 'prefix' => 'account'], function()
{
    //Authentication Routes
    Route::get('signin', 'AccountController@signin')->name('account.login');
    Route::post('auth/login', 'AccountController@authenticate');
    Route::get('signout','AccountController@signout')->name('account.logout');;

    //Dashboar Account routes
    Route::get('/','AccountController@index')->middleware(['auth']);
    Route::get('dashboard','AccountController@index')->middleware(['auth'])->name('account.index');;
});
/*
|-------------------------------------------------------------------------

/*
|--------------------------------------------------------------------------
| Application Routes
*/
Route::group(['middleware' => ['auth'], 'namespace' => 'App', 'prefix' => 'account/app'], function()
{
    //Dashboard
    Route::get('/', 'AppController@index');
    Route::get('dashboard/{filter?}', 'AppController@index')->where('filter','[A-Za-z]+')->name('account.dashboard');
    Route::any('search'   , 'SearchController@filter')->name('search.filter');

	Route::get('admission/filter/{type}','AdmissionController@filter')->name('admission.filter');
    Route::any('admission/status/{id}'  ,'AdmissionController@status')->name('admission.status');
    Route::resource('admission'   ,'AdmissionController');

	Route::any('fee/search'       ,'FeeController@search');
    Route::get('fee/pay/{id}'     ,'FeeController@pay')->name('fee.pay');
    Route::get('fee/filter/{type}','FeeController@filter')->name('fee.filter');
    Route::get('counsellor-fee','FeeController@counsellorfeesIndex')->name('counsellor.fees');
    Route::resource('fee' ,'FeeController');

    Route::post('employee/password/{id}' ,'EmployeeController@updatePassword')->name('employee.password');
	Route::resource('employee'   ,'EmployeeController');
    Route::resource('inquiry'    ,'InquiryController');
    Route::resource('role'       ,'RoleController');
    Route::resource('course'     ,'CourseController');

    Route::any('certificate/search'    ,'CertificateController@search')->name('certificate.search');
    Route::get('certificate/request'   ,'CertificateController@requests')->name('certificate.request');
    Route::get('authorise/certificate/{id}'   ,'CertificateController@authorise')->name('certificate.authorise');
    Route::get('issue/certificate/{id}','CertificateController@issueCertificate')->name('issue.certificate');
    Route::get('certificate/issue/{id}','CertificateController@issue')->name('certificate.issue');
    Route::resource('certificate'      ,'CertificateController');

    Route::any('reports/search','ReportsController@filter')->name('reports.filter');
    Route::resource('reports' ,'ReportsController');

    Route::get('performance/filter/{type}','PerformanceController@filter')->name('performance.filter');
    Route::resource('performance' ,'PerformanceController');

    Route::any('update-batch/{id}/edit','BatchController@editBatch')->name('batch.edit_batch');
    Route::any('assign-batch','BatchController@assignBatch')->name('batch.assign');
    Route::get('batch-assigned/{filter?}' ,'BatchController@assignedBatches')->name('batch.assigned');
    Route::get('batch-unassign/{id}' ,'BatchController@unassignBatch')->name('batch.unassign');
    Route::get('my-batch/{filter?}'  ,'BatchController@trainerBatch')->name('batch.trainer');

    Route::resource('batch' ,'BatchController');
    Route::resource('batch-category' ,'BatchCategoryController');

    Route::get('attendance/admin/{filter}' ,'AttendanceController@indexAdmin')->name('attendance.admin');
    Route::get('attendance/make/{filter?}' ,'AttendanceController@indexMake')->name('attendance.make');
    Route::post('attendance/admin-store' ,'AttendanceController@storeAdmin')->name('attendance.admin_create');

    Route::get('get-attendance/{id}' ,'AttendanceController@getAttendance');
    Route::get('attendance/my/{filter}' ,'AttendanceController@indexToday')->name('attendance.today');
    Route::resource('attendance' ,'AttendanceController');
    Route::resource('reviews' ,'ReviewsController');

});


Route::group(['namespace' => 'Student', 'prefix' => 'student'], function()
{
    //Authentication Routes
    Route::get('signin', 'StudentController@signin')->name('student.login');
    Route::post('auth/login', 'StudentController@authenticate')->name('login.student');
    Route::get('signout','StudentController@signout')->name('student.logout');

    //Dashboar Account routes
    // Route::get('/','StudentController@index');
    Route::get('dashboard','StudentController@dashboard')->name('student.dashboard');
    Route::match(['get','post'],'review/trainer','StudentController@reviewTrainer')->name('review.trainer');
    Route::get('apply/certificate','StudentController@applyCertificate')->name('apply.certificate');
});

/*
|-------------------------------------------------------------------------- */

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    //
    protected $table      = 'course';
    protected $primaryKey = 'id';
    protected $fillable = ['name', 'status'];
    protected $guarded  = [];
    protected $hidden   = ['created_at'];
}

resources/views/app/pages/course/edit.blade.php
@extends('app.layout.app')
@section('title','Edit Course')
@section('content')
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h2 class="box-title"><b>Edit Course</b></h2>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse"> <i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    @if($errors->count())
                    @foreach ($errors->all() as $message)
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ $message }}
                    </div>
                    @endforeach
                    @endif

                    <form name="courseForm" id="courseForm" method="POST" action="{{ route('course.update',['id' => $course->id ]) }}" data-toggle="validator">
                        @csrf
                        @method('PUT')

                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Course Name</label>
                                    <input type="text" class="form-control" name="name" placeholder="Enter Course Name"
                                        value="{{ $course->name }}" autocomplete="false" required="required" style="text-transform: uppercase;">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Status</label>
                                    <select name="status" class="form-control">
                                        <option value="1" @if($course->status == 1) selected @endif>Active</option>
                                        <option value="0" @if($course->status == 0) selected @endif>Suspend</option>
                                    </select>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-lg btn-block btn-danger">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

@push('styles')

@endpush

@push('scripts')

@endpush

resources/views/app/pages/course/index.blade.php
@extends('app.layout.app')
@section('title','Courses')
@section('mod_title','Course View')
@section('content')
<!-- Main content -->
<section class="content">
    
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h2 class="box-title"><b>Courses Manager</b></h2>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                            <i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    <div class="row" style="padding: 10px;">
                        <div class="col-md-12">
                        <a href="{{ route('course.create') }}" class="btn btn-md btn-danger"><i class="fa fa-plus"></i> New Course</a>
                            <hr>
                        </div>
                    </div>

                    @if(session('status'))
                    <div class="alert alert-success" id="msg-alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="color: white">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <p style="font-size: 18px"><strong>{{ session('status') }}</strong></p>
                    </div>
                    @endif

                    <table id="data-table" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Course Name</th>
                                <th>Status</th>                                                                
                                @if(Auth::user()->getRole->can_view == 1)                                
                                    <th>Actions</th>
                                @endif
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($course as $key => $crse)   
                            <tr>
                                <td>{{ $key+1 }}</td>
                                <td>{{ strtoupper($crse->name) }}</td>                                
                                <td>
                                    @if($crse->status == '1')
                                        <span class="label label-success">ACTIVE</span>
                                    @elseif($crse->status == '2')
                                        <span class="label label-danger">DELETED</span>
                                    @elseif($crse->status == '0')
                                        <span class="label label-danger">SUSPENDED</span>
                                    @endif
                                </td>
                                @if(Auth::user()->getRole->can_view == 1)
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-danger btn-flat openBtn big" data-href="{{ route('course.show',['id' => $crse->id ]) }}" href="javascript:void(0);"><i class="fa fa-eye"></i> View</a>
                                          <a class="btn btn-danger btn-flat dropdown-toggle big" data-toggle="dropdown">
                                            <span class="caret"></span>
                                            <span class="sr-only">Toggle Dropdown</span>
                                          </a>
                                          <ul class="dropdown-menu big" role="menu">
                                            @if(Auth::user()->getRole->can_update == 1)
                                                <li><a href="{{ route('course.edit',['id' => $crse->id ]) }}"><i class="fa fa-pencil"></i> Edit</a></li>
                                            @endif
                                            @if(Auth::user()->getRole->can_remove == 1)
                                                <li>
                                                    <a href="javascript:void(0);" onclick="deleteRecord('{{ route('course.destroy',['id' => $crse->id ]) }}')">
                                                        <i class="fa fa-trash"></i> Delete
                                                    </a>
                                                </li>
                                            @endif
                                          </ul>
                                    </div>
                                </td>
                                @endif

                            </tr>
                            @endforeach
                            
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Course Name</th>
                                <th>Status</th> 
                                @if(Auth::user()->getRole->can_view == 1)                                
                                    <th>&nbsp;</th>
                                @endif
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

@push('styles')
   <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset(config('app.prefix').'components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  <style>
      th { font-size: 16px; }
      td { font-size: 18px; }
      .big{
        font-size: 12px;
        font-weight: bold;
      }
  </style>
@endpush

@push('scripts')
<!-- DataTables -->
<script src="{{ asset(config('app.prefix').'components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset(config('app.prefix').'components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<script>
    $(function () {
        $('#data-table').DataTable({
            "aaSorting": [],
        });
    })
</script>
@endpush

resources/views/app/pages/course/new.blade.php
@extends('app.layout.app')
@section('title','Add Course')
@section('content')
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h2 class="box-title"><b>Add Course</b></h2>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse"> <i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    @if($errors->count())
                    @foreach ($errors->all() as $message)
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ $message }}
                    </div>
                    @endforeach
                    @endif

                    <form name="courseForm" id="courseForm" method="POST" action="../course" data-toggle="validator">
                        @csrf


                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Course Name</label>
                                    <input type="text" class="form-control" name="name" placeholder="Enter Course Name"
                                        value="{{ old('name') }}" required="required" style="text-transform: uppercase;">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Status</label>
                                    <select name="status" class="form-control">
                                        <option value="1">Active</option>
                                        <option value="0">Suspend</option>
                                    </select>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-lg btn-block btn-danger">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

@push('styles')

@endpush

@push('scripts')

@endpush

resources/views/app/pages/course/view.blade.php
<!-- Main content -->
<section class="content">
        <!-- Custom Tabs -->
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_personel" data-toggle="tab">Details</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_personel">
                    <table class="table table-bordered table-hover table-condensed">
                        <tbody>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">Course Name:</td>
                            <td class="techSpecTD2">{{ strtoupper($course->name) }}</td>
                          </tr>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">Status:</td>
                            <td class="techSpecTD2">
                                @if($course->status == 1)
                                    <span class="label label-success">ACTIVE</span>
                                @elseif($course->status == 2)
                                    <span class="label label-danger">DELETED</span>
                                @elseif($course->status == 0)
                                    <span class="label label-warning">IN-ACTIVE</span>
                                @endif
                            </td>
                          </tr>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">Created On:</td>
                            <td class="techSpecTD2">{{ date('d-m-Y',strtotime($course->created_at)) }}</td>
                          </tr>
                        </tbody>
                      </table>
                </div>
    
               
            </div>
            <!-- /.tab-content -->
        </div>
        <!-- nav-tabs-custom -->
    </section>