routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
Route::get('/', function ()
{
    if(Auth::check()){
        return redirect()->intended('account/app/dashboard');
    }else{
        return redirect()->intended('account/signin');
    }
});
/*
|-------------------------------------------------------------------------


/*
|--------------------------------------------------------------------------
| Account/Auth Routes
*/
Route::group(['namespace' => 'Account', 'prefix' => 'account'], function()
{
    //Authentication Routes
    Route::get('signin', 'AccountController@signin')->name('account.login');
    Route::post('auth/login', 'AccountController@authenticate');
    Route::get('signout','AccountController@signout')->name('account.logout');;

    //Dashboar Account routes
    Route::get('/','AccountController@index')->middleware(['auth']);
    Route::get('dashboard','AccountController@index')->middleware(['auth'])->name('account.index');;
});
/*
|-------------------------------------------------------------------------

/*
|--------------------------------------------------------------------------
| Application Routes
*/
Route::group(['middleware' => ['auth'], 'namespace' => 'App', 'prefix' => 'account/app'], function()
{
    //Dashboard
    Route::get('/', 'AppController@index');
    Route::get('dashboard/{filter?}', 'AppController@index')->where('filter','[A-Za-z]+')->name('account.dashboard');
    Route::any('search'   , 'SearchController@filter')->name('search.filter');

	Route::get('admission/filter/{type}','AdmissionController@filter')->name('admission.filter');
    Route::any('admission/status/{id}'  ,'AdmissionController@status')->name('admission.status');
    Route::resource('admission'   ,'AdmissionController');

	Route::any('fee/search'       ,'FeeController@search');
    Route::get('fee/pay/{id}'     ,'FeeController@pay')->name('fee.pay');
    Route::get('fee/filter/{type}','FeeController@filter')->name('fee.filter');
    Route::get('counsellor-fee','FeeController@counsellorfeesIndex')->name('counsellor.fees');
    Route::resource('fee' ,'FeeController');

    Route::post('employee/password/{id}' ,'EmployeeController@updatePassword')->name('employee.password');
	Route::resource('employee'   ,'EmployeeController');
    Route::resource('inquiry'    ,'InquiryController');
    Route::resource('role'       ,'RoleController');
    Route::resource('course'     ,'CourseController');

    Route::any('certificate/search'    ,'CertificateController@search')->name('certificate.search');
    Route::get('certificate/request'   ,'CertificateController@requests')->name('certificate.request');
    Route::get('authorise/certificate/{id}'   ,'CertificateController@authorise')->name('certificate.authorise');
    Route::get('issue/certificate/{id}','CertificateController@issueCertificate')->name('issue.certificate');
    Route::get('certificate/issue/{id}','CertificateController@issue')->name('certificate.issue');
    Route::resource('certificate'      ,'CertificateController');

    Route::any('reports/search','ReportsController@filter')->name('reports.filter');
    Route::resource('reports' ,'ReportsController');

    Route::get('performance/filter/{type}','PerformanceController@filter')->name('performance.filter');
    Route::resource('performance' ,'PerformanceController');

    Route::any('update-batch/{id}/edit','BatchController@editBatch')->name('batch.edit_batch');
    Route::any('assign-batch','BatchController@assignBatch')->name('batch.assign');
    Route::get('batch-assigned/{filter?}' ,'BatchController@assignedBatches')->name('batch.assigned');
    Route::get('batch-unassign/{id}' ,'BatchController@unassignBatch')->name('batch.unassign');
    Route::get('my-batch/{filter?}'  ,'BatchController@trainerBatch')->name('batch.trainer');

    Route::resource('batch' ,'BatchController');
    Route::resource('batch-category' ,'BatchCategoryController');

    Route::get('attendance/admin/{filter}' ,'AttendanceController@indexAdmin')->name('attendance.admin');
    Route::get('attendance/make/{filter?}' ,'AttendanceController@indexMake')->name('attendance.make');
    Route::post('attendance/admin-store' ,'AttendanceController@storeAdmin')->name('attendance.admin_create');

    Route::get('get-attendance/{id}' ,'AttendanceController@getAttendance');
    Route::get('attendance/my/{filter}' ,'AttendanceController@indexToday')->name('attendance.today');
    Route::resource('attendance' ,'AttendanceController');
    Route::resource('reviews' ,'ReviewsController');

});


Route::group(['namespace' => 'Student', 'prefix' => 'student'], function()
{
    //Authentication Routes
    Route::get('signin', 'StudentController@signin')->name('student.login');
    Route::post('auth/login', 'StudentController@authenticate')->name('login.student');
    Route::get('signout','StudentController@signout')->name('student.logout');

    //Dashboar Account routes
    // Route::get('/','StudentController@index');
    Route::get('dashboard','StudentController@dashboard')->name('student.dashboard');
    Route::match(['get','post'],'review/trainer','StudentController@reviewTrainer')->name('review.trainer');
    Route::get('apply/certificate','StudentController@applyCertificate')->name('apply.certificate');
});

/*
|-------------------------------------------------------------------------- */

app/Models/Batch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Batch extends Model
{
    //
    protected $table      = 'batch';
    //protected $primaryKey = 'id';
    protected $fillable = [];
    protected $guarded  = [];
    protected $hidden   = [];

    public function category()
    {
        return $this->hasOne('App\Models\BatchCategory','id','category_id');
    }

    public function trainer(){
        return $this->hasOne('App\Models\Profile','id','trainer_id');
    }

    public function admissions(){
        return $this->hasMany('App\Models\Admissions','batch_id','id');
    }

    public function attendance(){
        return $this->hasMany('App\Models\Attendance','trainer_id','trainer_id');
    }

}

resources/views/app/pages/batch/category/index.blade.php
@extends('app.layout.app')
@section('title','Batche Category(s)')
@section('mod_title','Batch Category View')
@section('content')
<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h2 class="box-title"><b>Batch Category Manager</b></h2>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse">
                            <i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    <div class="row" style="padding: 10px;">
                        <div class="col-md-12">
                        <a href="{{ route('batch-category.create') }}" class="btn btn-md btn-danger"><i class="fa fa-plus"></i> New Batch Category</a>
                            <hr>
                        </div>
                    </div>

                    @if(session('status'))
                    <div class="alert alert-success" id="msg-alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="color: white">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <p style="font-size: 18px"><strong>{{ session('status') }}</strong></p>
                    </div>
                    @endif

                    <table id="data-table" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Category Name</th>
                                <th>Status</th>
                                @if(Auth::user()->getRole->can_view == 1)
                                    <th>Actions</th>
                                @endif
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($batch as $key => $batch)
                            <tr>
                                <td>{{ $key+1 }}</td>
                                <td>{{ strtoupper($batch->name) }}</td>
                                <td>
                                    @if($batch->status == '1')
                                        <span class="label label-success">ACTIVE</span>
                                    @elseif($batch->status == '0')
                                        <span class="label label-danger">SUSPENDED</span>
                                    @endif
                                </td>
                                @if(Auth::user()->getRole->can_view == 1)
                                <td>
                                    <div class="btn-group">
                                        @if(Auth::user()->getRole->can_update == 1)
                                            <a class="btn btn-primary btn-flat" href="{{ route('batch-category.edit',['id' => $batch->id ]) }}"><i class="fa fa-pencil"></i> Edit</a>
                                        @endif
                                        @if(Auth::user()->getRole->can_remove == 1)
                                            <a class="btn btn-danger btn-flat "href="javascript:void(0);" onclick="deleteRecord('{{ route('batch-category.destroy',['id' => $batch->id ]) }}')">
                                                <i class="fa fa-trash"></i> Delete
                                            </a>
                                        @endif
                                    </div>
                                </td>
                                @endif

                            </tr>
                            @endforeach

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Category Name</th>
                                <th>Status</th>
                                @if(Auth::user()->getRole->can_view == 1)
                                    <th>&nbsp;</th>
                                @endif
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

@push('styles')
   <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset(config('app.prefix').'components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  <style>
      th { font-size: 16px; }
      td { font-size: 18px; }
      .big{
        font-size: 12px;
        font-weight: bold;
      }
  </style>
@endpush

@push('scripts')
<!-- DataTables -->
<script src="{{ asset(config('app.prefix').'components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset(config('app.prefix').'components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<script>
    $(function () {
        $('#data-table').DataTable({
            "aaSorting": [],
        });
    })
</script>
@endpush

resources/views/app/pages/batch/category/new.blade.php
@extends('app.layout.app')
@section('title','Add Batch Category')
@section('content')
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h2 class="box-title"><b>Add Batch Category</b></h2>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse"> <i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    @if($errors->count())
                    @foreach ($errors->all() as $message)
                    <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ $message }}
                    </div>
                    @endforeach
                    @endif

                    <form name="courseForm" id="courseForm" method="POST" action="{{ route('batch-category.store') }}" data-toggle="validator">
                        @csrf

                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Category Name</label>
                                    <input type="text" class="form-control" name="name" placeholder="Enter Category Name"
                                        value="{{ old('name') }}" required="required" style="text-transform: uppercase;">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Status</label>
                                    <select name="status" class="form-control">
                                        <option value="1">Active</option>
                                        <option value="0">Suspend</option>
                                    </select>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-lg btn-block btn-danger">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

@push('styles')

@endpush

@push('scripts')

@endpush