routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
Route::get('/', function ()
{
    if(Auth::check()){
        return redirect()->intended('account/app/dashboard');
    }else{
        return redirect()->intended('account/signin');
    }
});
/*
|-------------------------------------------------------------------------


/*
|--------------------------------------------------------------------------
| Account/Auth Routes
*/
Route::group(['namespace' => 'Account', 'prefix' => 'account'], function()
{
    //Authentication Routes
    Route::get('signin', 'AccountController@signin')->name('account.login');
    Route::post('auth/login', 'AccountController@authenticate');
    Route::get('signout','AccountController@signout')->name('account.logout');;

    //Dashboar Account routes
    Route::get('/','AccountController@index')->middleware(['auth']);
    Route::get('dashboard','AccountController@index')->middleware(['auth'])->name('account.index');;
});
/*
|-------------------------------------------------------------------------

/*
|--------------------------------------------------------------------------
| Application Routes
*/
Route::group(['middleware' => ['auth'], 'namespace' => 'App', 'prefix' => 'account/app'], function()
{
    //Dashboard
    Route::get('/', 'AppController@index');
    Route::get('dashboard/{filter?}', 'AppController@index')->where('filter','[A-Za-z]+')->name('account.dashboard');
    Route::any('search'   , 'SearchController@filter')->name('search.filter');

	Route::get('admission/filter/{type}','AdmissionController@filter')->name('admission.filter');
    Route::any('admission/status/{id}'  ,'AdmissionController@status')->name('admission.status');
    Route::resource('admission'   ,'AdmissionController');

	Route::any('fee/search'       ,'FeeController@search');
    Route::get('fee/pay/{id}'     ,'FeeController@pay')->name('fee.pay');
    Route::get('fee/filter/{type}','FeeController@filter')->name('fee.filter');
    Route::get('counsellor-fee','FeeController@counsellorfeesIndex')->name('counsellor.fees');
    Route::resource('fee' ,'FeeController');

    Route::post('employee/password/{id}' ,'EmployeeController@updatePassword')->name('employee.password');
	Route::resource('employee'   ,'EmployeeController');
    Route::resource('inquiry'    ,'InquiryController');
    Route::resource('role'       ,'RoleController');
    Route::resource('course'     ,'CourseController');

    Route::any('certificate/search'    ,'CertificateController@search')->name('certificate.search');
    Route::get('certificate/request'   ,'CertificateController@requests')->name('certificate.request');
    Route::get('authorise/certificate/{id}'   ,'CertificateController@authorise')->name('certificate.authorise');
    Route::get('issue/certificate/{id}','CertificateController@issueCertificate')->name('issue.certificate');
    Route::get('certificate/issue/{id}','CertificateController@issue')->name('certificate.issue');
    Route::resource('certificate'      ,'CertificateController');

    Route::any('reports/search','ReportsController@filter')->name('reports.filter');
    Route::resource('reports' ,'ReportsController');

    Route::get('performance/filter/{type}','PerformanceController@filter')->name('performance.filter');
    Route::resource('performance' ,'PerformanceController');

    Route::any('update-batch/{id}/edit','BatchController@editBatch')->name('batch.edit_batch');
    Route::any('assign-batch','BatchController@assignBatch')->name('batch.assign');
    Route::get('batch-assigned/{filter?}' ,'BatchController@assignedBatches')->name('batch.assigned');
    Route::get('batch-unassign/{id}' ,'BatchController@unassignBatch')->name('batch.unassign');
    Route::get('my-batch/{filter?}'  ,'BatchController@trainerBatch')->name('batch.trainer');

    Route::resource('batch' ,'BatchController');
    Route::resource('batch-category' ,'BatchCategoryController');

    Route::get('attendance/admin/{filter}' ,'AttendanceController@indexAdmin')->name('attendance.admin');
    Route::get('attendance/make/{filter?}' ,'AttendanceController@indexMake')->name('attendance.make');
    Route::post('attendance/admin-store' ,'AttendanceController@storeAdmin')->name('attendance.admin_create');

    Route::get('get-attendance/{id}' ,'AttendanceController@getAttendance');
    Route::get('attendance/my/{filter}' ,'AttendanceController@indexToday')->name('attendance.today');
    Route::resource('attendance' ,'AttendanceController');
    Route::resource('reviews' ,'ReviewsController');

});


Route::group(['namespace' => 'Student', 'prefix' => 'student'], function()
{
    //Authentication Routes
    Route::get('signin', 'StudentController@signin')->name('student.login');
    Route::post('auth/login', 'StudentController@authenticate')->name('login.student');
    Route::get('signout','StudentController@signout')->name('student.logout');

    //Dashboar Account routes
    // Route::get('/','StudentController@index');
    Route::get('dashboard','StudentController@dashboard')->name('student.dashboard');
    Route::match(['get','post'],'review/trainer','StudentController@reviewTrainer')->name('review.trainer');
    Route::get('apply/certificate','StudentController@applyCertificate')->name('apply.certificate');
});

/*
|-------------------------------------------------------------------------- */

resources/views/app/inc/sidebar/admin.blade.php
<li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'admission')? 'treeview active' : ''; }?>">
    <a href="#">
      <i class="fa fa-university"></i>
      <span>Admissions</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li class="@if(url()->current() == route('admission.index').'/filter/today')  active @endif"><a href="{{ route('admission.index') }}/filter/today"><i class="fa fa-circle-o"></i> All Admissions</a></li>
      <li class="@if(url()->current() == route('admission.create')) active @endif"><a href="/account/app/admission/create"><i class="fa fa-circle-o"></i> New Admission</a></li>
    </ul>
</li>

<li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'fee')? 'treeview active' : ''; }?>">
    <a href="#">
      <i class="fa fa-rupee"></i>
      <span>Fees</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="/account/app/fee"><i class="fa fa-circle-o"></i> All Fees</a></li>
      <li><a href="/account/app/fee/search"><i class="fa fa-circle-o"></i> Pay Fee</a></li>
    </ul>
</li>

<li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'batch' || $uriP[2] == 'batch-category' || $uriP[2] == 'batch-assigned')? 'treeview active' : ''; }?>">
    <a href="#">
      <i class="fa fa-bell-o"></i>
      <span>Batches</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
        <li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'batch-category')? 'treeview active' : ''; }?>">
            <a href="#"><i class="fa fa-circle-o"></i> Batch Categories
                <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li class="@if(url()->current() == route('batch-category.index'))  active @endif"><a href="{{ route('batch-category.index') }}"><i class="fa fa-circle-o"></i> All Categorie(s)</a></li>
                <li class="@if(url()->current() == route('batch-category.create'))  active @endif"><a href="{{ route('batch-category.create') }}"><i class="fa fa-circle-o"></i> New Category</a></li>
            </ul>
        </li>

        <li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'batch')? 'treeview active' : ''; }?>">
            <a href="#"><i class="fa fa-circle-o"></i> Batches
                <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li class="@if(url()->current() == route('batch.index'))  active @endif"><a href="{{ route('batch.index') }}"><i class="fa fa-circle-o"></i> All Batches</a></li>
                <li class="@if(url()->current() == route('batch.create')) active @endif"><a href="{{ route('batch.create') }}"><i class="fa fa-circle-o"></i> New Batch</a></li>
            </ul>
        </li>
        <li class="@if(url()->current() == route('batch.assigned',['filter' => 'all'] ))  active @endif"><a href="{{ route('batch.assigned',['filter' => 'all']) }}"><i class="fa fa-circle-o"></i> Assigned Batches</a></li>
    </ul>
</li>

<li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'attendance')? 'treeview active' : ''; }?>">
    <a href="#">
      <i class="fa fa-calendar-check-o"></i>
      <span>Attendance</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li class="@if(url()->current() == route('attendance.admin',['filter' => 'all']))  active @endif"><a href="/account/app/attendance/admin/all"><i class="fa fa-circle-o"></i> View Attendance</a></li>
      <li class="@if(url()->current() == route('attendance.make'))  active @endif"><a href="{{ route('attendance.make') }}"><i class="fa fa-circle-o"></i> Make Attendance</a></li>
    </ul>
</li>
<li class="<?php if(isset($uriP[1])){ echo ($uriP[2] == 'reviews')? 'active' : ''; }?>"><a href="/account/app/reviews"><i class="fa fa-star"></i> <span>Reviews</span></a></li>
<li class="<?php if(isset($uriP[1])){ echo ($uriP[2] == 'reports')? 'active' : ''; }?>"><a href="/account/app/reports"><i class="fa fa-area-chart"></i> <span>Reports</span></a></li>

<li class="header">Advanced</li>

  <li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'role')? 'treeview active' : ''; }?>">
    <a href="#">
      <i class="fa fa-lock"></i>
      <span>Roles</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="/account/app/role"><i class="fa fa-circle-o"></i> All Roles</a></li>
      <li><a href="/account/app/role/create"><i class="fa fa-circle-o"></i> Add Role</a></li>
    </ul>
  </li>

  <li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'employee')? 'treeview active' : ''; }?>">
    <a href="#">
      <i class="fa fa-group"></i>
      <span>Employees</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="/account/app/employee"><i class="fa fa-circle-o"></i> All Employees</a></li>
      <li><a href="/account/app/employee/create"><i class="fa fa-circle-o"></i> Add Employee</a></li>
    </ul>
</li>

     <li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'course')? 'treeview active' : ''; }?>">
      <a href="#">
        <i class="fa fa-list"></i>
        <span>Courses</span>
        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
      </a>
      <ul class="treeview-menu">
        <li><a href="/account/app/course"><i class="fa fa-circle-o"></i> All Courses</a></li>
        <li><a href="/account/app/course/create"><i class="fa fa-circle-o"></i> Add Course</a></li>
      </ul>
  </li>

  <li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'certificate')? 'treeview active' : ''; }?>">
    <a href="#">
      <i class="fa fa-list-alt"></i>
      <span>Certificates</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li class="@if(url()->current() == route('certificate.index')) active @endif"><a href="{{ route('certificate.index')   }}"><i class="fa fa-circle-o"></i> Issue </a></li>
      <li class="@if(url()->current() == route('certificate.create')) active @endif"><a href="{{ route('certificate.create')  }}"><i class="fa fa-circle-o"></i> Print</a></li>
      <li class="@if(url()->current() == route('certificate.request')) active @endif"><a href="{{ route('certificate.request') }}"><i class="fa fa-circle-o"></i>New Requests</a></li>
    </ul>
  </li>

resources/views/app/inc/sidebar/counselor.blade.php
{{-- <li class="treeview //if(isset($uriP[1])){ echo ($uriP[2] == 'admission')? 'treeview active' : ''; }?>">
    <a href="#">
      <i class="fa fa-university"></i>
      <span>Admissions</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li class="@if(url()->current() == route('admission.index'))  active @endif"><a href="/account/app/admission"><i class="fa fa-circle-o"></i> All Admissions</a></li>
    </ul>
  </li> --}}

resources/views/app/inc/sidebar/student.blade.php
<li class="treeview <?php if(isset($uriP[0])){ echo ($uriP[1] == 'admission')? 'treeview active' : ''; }?>">
        <a href="#">
          <i class="fa fa-university"></i>
          <span>Admissions</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li class="@if(url()->current() == route('admission.index'))  active @endif"><a href="/account/app/admission"><i class="fa fa-circle-o"></i> All Admissions</a></li>
        </ul>
      </li>
    

resources/views/app/inc/sidebar/trainer.blade.php
<li class="<?php if(isset($uriP[1])){ echo ($uriP[2] == 'my-batch')? 'active' : ''; }?>"><a href="{{ route('batch.trainer') }}""><i class="fa fa-bell"></i> <span>My Batches</span></a></li>

<li class="treeview <?php if(isset($uriP[1])){ echo ($uriP[2] == 'attendance')? 'treeview active' : ''; }?>">
        <a href="#">
          <i class="fa fa-calendar-check-o"></i>
          <span>Attendance</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
            <li class="@if(url()->current() == route('attendance.today',['filter' => 'today']))  active @endif"><a href="/account/app/attendance/my/today"><i class="fa fa-circle-o"></i> Today</a></li>
            <li class="@if(url()->current() == route('attendance.index'))  active @endif"><a href="/account/app/attendance"><i class="fa fa-circle-o"></i> All</a></li>
        </ul>
    </li>