routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
Route::get('/', function ()
{
    if(Auth::check()){
        return redirect()->intended('account/app/dashboard');
    }else{
        return redirect()->intended('account/signin');
    }
});
/*
|-------------------------------------------------------------------------


/*
|--------------------------------------------------------------------------
| Account/Auth Routes
*/
Route::group(['namespace' => 'Account', 'prefix' => 'account'], function()
{
    //Authentication Routes
    Route::get('signin', 'AccountController@signin')->name('account.login');
    Route::post('auth/login', 'AccountController@authenticate');
    Route::get('signout','AccountController@signout')->name('account.logout');;

    //Dashboar Account routes
    Route::get('/','AccountController@index')->middleware(['auth']);
    Route::get('dashboard','AccountController@index')->middleware(['auth'])->name('account.index');;
});
/*
|-------------------------------------------------------------------------

/*
|--------------------------------------------------------------------------
| Application Routes
*/
Route::group(['middleware' => ['auth'], 'namespace' => 'App', 'prefix' => 'account/app'], function()
{
    //Dashboard
    Route::get('/', 'AppController@index');
    Route::get('dashboard/{filter?}', 'AppController@index')->where('filter','[A-Za-z]+')->name('account.dashboard');
    Route::any('search'   , 'SearchController@filter')->name('search.filter');

	Route::get('admission/filter/{type}','AdmissionController@filter')->name('admission.filter');
    Route::any('admission/status/{id}'  ,'AdmissionController@status')->name('admission.status');
    Route::resource('admission'   ,'AdmissionController');

	Route::any('fee/search'       ,'FeeController@search');
    Route::get('fee/pay/{id}'     ,'FeeController@pay')->name('fee.pay');
    Route::get('fee/filter/{type}','FeeController@filter')->name('fee.filter');
    Route::get('counsellor-fee','FeeController@counsellorfeesIndex')->name('counsellor.fees');
    Route::resource('fee' ,'FeeController');

    Route::post('employee/password/{id}' ,'EmployeeController@updatePassword')->name('employee.password');
	Route::resource('employee'   ,'EmployeeController');
    Route::resource('inquiry'    ,'InquiryController');
    Route::resource('role'       ,'RoleController');
    Route::resource('course'     ,'CourseController');

    Route::any('certificate/search'    ,'CertificateController@search')->name('certificate.search');
    Route::get('certificate/request'   ,'CertificateController@requests')->name('certificate.request');
    Route::get('authorise/certificate/{id}'   ,'CertificateController@authorise')->name('certificate.authorise');
    Route::get('issue/certificate/{id}','CertificateController@issueCertificate')->name('issue.certificate');
    Route::get('certificate/issue/{id}','CertificateController@issue')->name('certificate.issue');
    Route::resource('certificate'      ,'CertificateController');

    Route::any('reports/search','ReportsController@filter')->name('reports.filter');
    Route::resource('reports' ,'ReportsController');

    Route::get('performance/filter/{type}','PerformanceController@filter')->name('performance.filter');
    Route::resource('performance' ,'PerformanceController');

    Route::any('update-batch/{id}/edit','BatchController@editBatch')->name('batch.edit_batch');
    Route::any('assign-batch','BatchController@assignBatch')->name('batch.assign');
    Route::get('batch-assigned/{filter?}' ,'BatchController@assignedBatches')->name('batch.assigned');
    Route::get('batch-unassign/{id}' ,'BatchController@unassignBatch')->name('batch.unassign');
    Route::get('my-batch/{filter?}'  ,'BatchController@trainerBatch')->name('batch.trainer');

    Route::resource('batch' ,'BatchController');
    Route::resource('batch-category' ,'BatchCategoryController');

    Route::get('attendance/admin/{filter}' ,'AttendanceController@indexAdmin')->name('attendance.admin');
    Route::get('attendance/make/{filter?}' ,'AttendanceController@indexMake')->name('attendance.make');
    Route::post('attendance/admin-store' ,'AttendanceController@storeAdmin')->name('attendance.admin_create');

    Route::get('get-attendance/{id}' ,'AttendanceController@getAttendance');
    Route::get('attendance/my/{filter}' ,'AttendanceController@indexToday')->name('attendance.today');
    Route::resource('attendance' ,'AttendanceController');
    Route::resource('reviews' ,'ReviewsController');

});


Route::group(['namespace' => 'Student', 'prefix' => 'student'], function()
{
    //Authentication Routes
    Route::get('signin', 'StudentController@signin')->name('student.login');
    Route::post('auth/login', 'StudentController@authenticate')->name('login.student');
    Route::get('signout','StudentController@signout')->name('student.logout');

    //Dashboar Account routes
    // Route::get('/','StudentController@index');
    Route::get('dashboard','StudentController@dashboard')->name('student.dashboard');
    Route::match(['get','post'],'review/trainer','StudentController@reviewTrainer')->name('review.trainer');
    Route::get('apply/certificate','StudentController@applyCertificate')->name('apply.certificate');
});

/*
|-------------------------------------------------------------------------- */

resources/views/app/pages/employee/edit.blade.php
@extends('app.layout.app')
@section('title','Edit Employee')
@section('content')
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h2 class="box-title"><b>Edit Employee</b></h2>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                            title="Collapse"> <i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    @if($errors->count())
                        @foreach ($errors->all() as $message)
                            <div class="alert alert-danger" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                {{ $message }}
                            </div>
                        @endforeach
                    @endif

                    <form name="staffForm" id="staffForm" method="POST" action="{{ route('employee.update',['id' => $employee->id ]) }}" data-toggle="validator">
                    @csrf
                    @method('PUT')
                    
                    <fieldset>
                    <legend>Personel Information</legend>

                    <div class="row">
                            <div class="col-md-6">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Joining Date</label>
                                    <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                        <input type="text" class="form-control" name="join_date" id="datepicker" value="{{ date('d-m-Y',strtotime($employee->join_date)) }}"  required>
                                        </div>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                    <div class="form-group has-feedback">
                                        <label class="control-label">Set Profile Status</label>
                                        <select class="form-control" name="status" required>
                                            <option value="" selected>--Select Status--</option>
                                            <option value="active"  @if($employee->status == 'active') selected @endif>Active</option>
                                            <option value="suspend" @if($employee->status == 'suspend') selected @endif>Supend</option>
                                        </select>
                                        <div class="help-block with-errors"></div>
                                    </div>
                            </div>
                    </div>

                    <hr>
                        
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group has-feedback">
                                <label class="control-label">First Name</label>
                            <input type="text" class="form-control" name="first_name" placeholder="Enter First Name" value="{{ $employee->first_name }}" required="required">
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group has-feedback">
                                <label class="control-label">Last Name</label>
                                <input type="text" class="form-control" name="last_name" placeholder="Enter Last Name" value="{{ $employee->last_name }}" required="required">
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-md-4">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Phone</label>
                                    <input type="text" class="form-control" name="mobile" placeholder="Enter Phone Number" value="{{ $employee->mobile }}" required="required">
                                    <div class="help-block with-errors"></div>
                                </div>
                        </div>
                    </div>

                    <div class="row">
                            <div class="col-md-12">
                                <div class="form-group has-feedback">
                                    <label class="control-label">Address</label>
                                    <textarea class="form-control" name="address" placeholder="Enter Address Name" required="required">{{ $employee->address }}</textarea>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                    </div>

                    <div class="row">
                            <div class="col-md-4">
                                <div class="form-group has-feedback">
                                    <label class="control-label">City</label>
                                    <input type="text" class="form-control" name="city" placeholder="Enter City" value="{{ $employee->city }}" required="required">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group has-feedback">
                                    <label class="control-label">State</label>
                                    <input type="text" class="form-control" name="state" placeholder="Enter State" value="{{ $employee->state }}" required="required">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                    <div class="form-group has-feedback">
                                        <label class="control-label">Country</label>
                                        <input type="text" class="form-control" name="country" placeholder="Enter Country" value="{{ $employee->country }}" required="required" value="India">
                                        <div class="help-block with-errors"></div>
                                    </div>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset>
                        <legend>Login information</legend>
                        <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group has-feedback">
                                        <label class="control-label">Email/Username</label>
                                        <input type="email" class="form-control" name="user_name" placeholder="Enter Email" value="{{ $employee->user->email }}" readonly>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                
                                <div class="col-md-6">
                                    <div class="form-group has-feedback">
                                        <label class="control-label">User Role</label>
                                        <select class="form-control" name="role" required>
                                            <option value="" selected>--Select Role--</option>
                                            <option value="1" @if($employee->user->role == 1) selected @endif>Admin</option>
                                            <option value="2" @if($employee->user->role == 2) selected @endif>Center Manager</option>
                                            <option value="3" @if($employee->user->role == 3) selected @endif>Counsellor</option>
                                            <option value="4" @if($employee->user->role == 4) selected @endif>Accounts</option>
                                        </select>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                        </div>
                    </fieldset>

                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-lg btn-block btn-danger">Submit</button>
                        </div>
                    </div>
                    </form>

                    <hr>

                    <fieldset>
                            <form name="passwordForm" id="passwordForm" method="POST" action="{{ route('employee.password',['id' => $employee->id ]) }}" data-toggle="validator">
                            @csrf
                            <legend>Change Password</legend>
                            <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group has-feedback">
                                            <label class="control-label">Password</label>
                                            <input type="password" class="form-control" name="password" placeholder="Set Password" required="required">
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group has-feedback">
                                            <label class="control-label">Repeat Password</label>
                                            <input type="password" class="form-control" name="password_confirmation" placeholder="Repeat Password" required="required">
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group has-feedback">
                                            <label class="control-label">&nbsp;</label>
                                            <button type="submit" class="btn btn-sm btn-block btn-warning">Update</button>
                                        </div>
                                    </div>
                            </div>
                            </form>
                            </fieldset>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>

@endsection

@push('styles')
  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="{{ asset(config('app.prefix').'components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
@endpush

@push('scripts')
    <!-- bootstrap datepicker -->
    <script src="{{ asset(config('app.prefix').'components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $(function () {
            //Date picker
            $('#datepicker').datepicker({
                autoclose: true,
                format: "dd-mm-yyyy",
                todayBtn: true,
                clearBtn: true,
            })
        })
    </script>
@endpush

resources/views/app/pages/employee/index.blade.php
@extends('app.layout.app')
@section('title','All Employees')
@section('mod_title','Employee Profile')
@section('content')
<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h2 class="box-title"><b>Employee Manager</b></h2>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"> <i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    <div class="row" style="padding: 10px;">
                        <div class="col-md-12">
                        <a href="./employee/create" class="btn btn-md btn-danger"><i class="fa fa-plus"></i> Add Employee</a><hr>
                        </div>
                    </div>

                    @if(session('status'))
                        <div class="alert alert-success" id="msg-alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="color: white">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <p style="font-size: 18px"><strong>{{ session('status') }}</strong></p>
                        </div>
                    @endif
                    
                    <table id="data-table" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Phone</th>
                                <th>Address</th>
                                <th>Role</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($employee as $key => $emp)
                            <tr>
                                <td>{{ $key+1 }}</td>
                                <td>{{ ucwords($emp->first_name.' '.$emp->last_name) }}</td>
                                <td>{{ $emp->mobile }}</td>
                                <td>{{ ucwords($emp->address.', '.$emp->city) }}</td>
                                <td>
                                    @if($emp->getUserinfo->getRole->name == 'ADMIN')
                                        <span class="label label-success">ADMIN</span>
                                    @else
                                        <span class="label label-info">{{ strtoupper($emp->getUserinfo->getRole->name) }}</span>
                                    @endif
                                </td>
                                <td>
                                    @if($emp->status == 'active')
                                        <span class="label label-success">ACTIVE</span>
                                    @elseif($emp->status == 'trash')
                                        <span class="label label-danger">DELETED</span>
                                    @elseif($emp->status == 'suspend')
                                        <span class="label label-danger">SUSPEND</span>
                                    @endif
                                </td>
                                <td>
                                    <div class="btn-group">
                                    <a class="btn btn-danger btn-flat openBtn" data-href="{{ route('employee.show',['id' => $emp->id ]) }}" href="javascript:void(0);"><i class="fa fa-eye"></i> View</a>
                                        <a class="btn btn-danger btn-flat dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                            <span class="sr-only">Toggle Dropdown</span>
                                        </a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{{ route('employee.edit',['id' => $emp->user_id ]) }}"><i class="fa fa-pencil"></i> Edit</a></li>
                                            <li>
                                                <a href="javascript:void(0);" onclick="deleteRecord('{{ route('employee.destroy',['id' => $emp->id ]) }}')">
                                                    <i class="fa fa-trash"></i> Delete
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Phone</th>
                                <th>Address</th>
                                <th>Role</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
@endsection

@push('styles')
   <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset(config('app.prefix').'components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  <style>
      th { font-size: 16px; }
      td { font-size: 18px; }
      .big{
        font-size: 12px;
        font-weight: bold;
      }
  </style>
@endpush

@push('scripts')
<!-- DataTables -->
<script src="{{ asset(config('app.prefix').'components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset(config('app.prefix').'components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<script>
    $(function () {
        $('#data-table').DataTable({
            "aaSorting": [],
        });
    })
</script>
@endpush

resources/views/app/pages/employee/view.blade.php
<!-- Main content -->
<section class="content">
        <!-- Custom Tabs -->
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_personel" data-toggle="tab">Personel Details</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_personel">
                    <table class="table table-bordered table-hover table-condensed">
                        <tbody>
                          <tr class="techSpecRow" style="border: 1px dotted red">
                            <td class="techSpecTD1">Username/Email:</td>
                            <td class="techSpecTD2">{{ $employee->user->email }}</td>
                          </tr>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">Name:</td>
                            <td class="techSpecTD2">{{ ucwords($employee->first_name.' '.$employee->last_name) }}</td>
                          </tr>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">Mobile:</td>
                            <td class="techSpecTD2">{{ $employee->mobile }}</td>
                          </tr>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">Address:</td>
                            <td class="techSpecTD2">{{ ucwords($employee->address) }}</td>
                          </tr>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">City / State:</td>
                            <td class="techSpecTD2">{{ ucwords($employee->city.' / '.$employee->state) }}</td>
                          </tr>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">Country:</td>
                            <td class="techSpecTD2">{{ ucwords($employee->country) }}</td>
                          </tr>
                          <tr class="techSpecRow">
                            <td class="techSpecTD1">Joined On:</td>
                            <td class="techSpecTD2">{{ date('d-m-Y',strtotime($employee->join_date)) }}</td>
                          </tr>
                        </tbody>
                      </table>
                </div>
    
               
            </div>
            <!-- /.tab-content -->
        </div>
        <!-- nav-tabs-custom -->
    </section>